name: Build AAB

on:
  workflow_dispatch:

  push:
    paths:
      - 'src/android/**'
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Build AAB avec Buildozer
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/home/user/hostcwd
          run: |
            cd /home/user/hostcwd/src/android

            # Buildozer exige un point d'entrée nommé main.py
            cp main_android.py main.py

            # Génération du Android App Bundle
            yes | buildozer android release

      - name: Upload du AAB généré
        uses: actions/upload-artifact@v4
        with:
          name: neon-run-aab
          path: src/android/bin/*.aab
          if-no-files-found: error
